### PR TITLE
Use multi-line string for asset statements

### PR DESCRIPTION
**Pull request by rayankans**
It just makes the thing more readable.

### CODE REVIEW

**Comment by PEConn** [comment]
I'm surprised that this works, but with Andre's LGTM I'm happy with it.

**Comment by rayankans** [comment]
To be clear, I tried this and it works.

**Comment by andreban** [comment]
That's Groovy's multi-line String (https://groovy-lang.org/syntax.html). This should indeed work.

nit: Adding a `\` at the end of the first line will remove the new line introduced at the beginning of the string. The new line shouldn't be issue, but it sounds like removing it is a good idea?

**Comment by rayankans** [comment]
I tried adding the `\`, but the generated resources are the same. The newline was already ignored it seems. I don't think the change is necessary

**Pull request merged**
